### ISSUE TITLE
Review: usage with passport-local strategy

### ISSUE THREAD

**Issue by lirantal** [lirantal/nodejssecurity#5]
Reference: original review notes by @sosana: https://github.com/lirantal/nodejssecurity/issues/2

# usage with passport-local strategy
probably one of the most straight fwd implementation that quickly wires up securing api-end points with auth module of your choice (JWT or Cookie/Sessions)

my suggestion is to elaborate more on why you would want to consider using this and why its one of the most used local auth stradegy. In a world where everything seems to be going microservices (ex: api servers and seperatation of the front-end) vs monolith architecture.

# talk a about use of JSON Web Tokens.

Very easy to wire up, ex: using passport-jwt strategy
my suggestion is to elaborate more on this subject and provide example

**Comment by lirantal** [comment]
@sosana can you elaborate what did you have in mind exactly?

I'm not covering any authentication type or implementation at all in the book, so were you hoping that we could also be adding a topic that covers how to authenticate API?

If so, I'm wondering if it doesn't go beyond the topics of secure code and Node.js security because then it opens an entire subject of authentication and authorization. I combined this issue with the JWT comment here because it seems very connected to me with the whole auth topic.

**Comment by SOSANA** [comment]
@lirantal I was elaborating more on your use case for session management. I was referring to securing api end points and session support with jwt as alternative to cookies/sessions.

```
Secure Session Management
If your web application is completely stateless and requires no user customization at all, and no user
tracking then you probably don’t even need to worry about users and sessions management.
The other scenario is that you need to serve content customized for users, allow them to login and
perform some actions, or maintain a user related activity. This is where things get tricky and need
proper attention to whole lot more details of information security.
HTTP being a stateless communication protocol, there-fore creating the need for a mechanism to
track and maintain user’s actions when interacting with a web applications - sessions.
The focus of this chapter will discuss Cookies based session management which is the most widespread
way of maintaining sessions for web applications.
```
Let's close this bad boy, as your feed back gave me clarity with your focus on the book ;)

**Comment by lirantal** [comment]
Cool, though I do agree that probably a section about securing endpoints that would cover the different protocols and implementations such as general Sessions, OAuth, and JWT has it's place.
